### ISSUE TITLE
Bug: Symlink Fails for Scoped Package `@scope/package-name` with EPERM Error

### ISSUE THREAD

**Issue by derdeka** [isaacs/tshy#10]
#### Description

When attempting to use tshy for the scoped npm package `@scope/package-name`, the operation fails with an `EPERM: operation not permitted` error.

#### Steps to Reproduce

1. Navigate to the project folder `C:\Path\To\Your\Project\packages\some-package`
2. in `package.json` use name `@scope/package-name` or similar for package
3. Run the `npm i` that triggers `tshy` package symlink creation.
4. Observe the error.

#### Expected Behavior

The symlink for the `@scope/package-name` package should be created successfully.

#### Actual Behavior

The operation fails and throws the following error:

```
Error: EPERM: operation not permitted, symlink '..\..\..' -> 'C:\Path\To\Your\Project\packages\some-package\src\node_modules\@scope\package-name'
```

#### Environment

- Node.js version: 18.18.0
- Operating System: Windows
- tshy version: 1.2.2

#### Additional Information

- This error specifically occurs at the following lines in the `self-dep.js` file:
https://github.com/isaacs/tshy/blob/528f8d5b95025f5783e096316b13e28703af6a20/src/self-dep.ts#L55-L60

- Error Stack:
  ```
  at symlinkSync (node:fs:1816:3)
  at link (file:///C:/Path/To/Your/Project/packages/some-package/node_modules/tshy/dist/esm/self-dep.js:52:9)
  at default (file:///C:/Path/To/Your/Project/packages/some-package/node_modules/tshy/dist/esm/build.js:16:5)
  at file:///C:/Path/To/Your/Project/packages/some-package/node_modules/tshy/dist/esm/index.js:11:7
  at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
  ```

**Comment by isaacs** [comment]
Does it work if it's _not_ a scoped package?

I think this might just be a windows symlink permissions issue. Can you create directory symlinks in node to other locations?

If you can, and it's only scoped packages where it fails, then that's very interesting.

**Comment by isaacs** [comment]
Will reopen if more details provided. In the meantime, closing to remove from my todo list.

Possible workaround: set `{ "tshy": { "selfLink": false }}`
