### ISSUE TITLE
tshy is TooShy about emitting errors

### ISSUE THREAD

**Issue by boneskull** [isaacs/tshy#37]
You need to use `TSHY_VERBOSE=2` to see any compiler errors.  I feel like these should probably just be passed thru stderr by default?

**Comment by isaacs** [comment]
Ahh, yes, it only prints the diagnostics when the build fails, but you probably do want those warnings in any case. The tsc command should just inherit stdio.

**Comment by isaacs** [comment]
Do you have strict:true in tsconfig? I usually do have that set, probably why I haven't noticed this issue, since anything that has diags to print will also exit in error.

**Comment by isaacs** [comment]
Hm, looking at this, it seems like it [already uses `stdio:inherit`](https://github.com/isaacs/tshy/blob/main/src/build-esm.ts#L18-L21). Are you using the latest version? Do you have a project where I can see it not output diagnostics that you'd expect it to?

**Comment by isaacs** [comment]
Will re-open when more details provided.
