### ISSUE TITLE
Option to exclude files from compilation

### ISSUE THREAD

**Issue by DaniGuardiola** [isaacs/tshy#44]
I want to exclude my tests (which are contained in `src/`) from being compiled by tshy. How can I do this?

Putting them somewhere else is unfortunately not an option due to the context of the project.

**Comment by isaacs** [comment]
Hm, yeah, it'd be nice if you could explicitly exclude things from _all_ builds. Right now you can exclude them from a dialect or include in a dialect build, but no way to exclude them from the build entirely.

How would this strike you?

```json
{
  "tshy": {
    "exclude": ["src/**/*.test.ts"]
  }
}
```

Then it'd just combine that with whatever else it puts in the `tsconfig` for each dialect build.

**Comment by DaniGuardiola** [comment]
That API is exactly what I need :)
