### ISSUE TITLE
Feature request: add option to preserve comments only in *.d.ts files

### ISSUE THREAD

**Issue by starnayuta** [isaacs/tshy#45]
Some people who be developing closed source software would like to strip out any internal comments but preserve any JSDocs comments.

TypeScript features cannot achieve this.  
There is a way to achieve this by setting removeComments to false for type and to true for JavaScript.  
https://github.com/microsoft/TypeScript/issues/14619#issuecomment-784973548

``` json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "declaration": false,
    "removeComments": true
  },
}
```

``` json
"scripts": {
  "build": "tsc",
  "build:nocomments": "tsc -p ./tsconfig.nocomments.json",
  "prod": "npm run build && npm run build:nocomments"
},
```

The tshy uses the same tsconfig for JavaScript and type.  
How about providing a way to load multiple tsconfigs and run tsc, or provide a specific option?

Thank you for a great library.

**Comment by starnayuta** [comment]
I have found that all we need to do is change the [project](https://github.com/isaacs/tshy#custom-project) and run tshy twice.

However, as tshy deletes and creates the dist, dist/esm and dist/commonjs need to be temporarily stored elsewhere.

So we need to do the following

1. specify tsconfig.json with `"removeComments": false` in project
2. run tshy
3. cache dist/commonjs and dist/esm
4. put tsconfig.json with `"removeComments": true` and  `"declaration": false` in project
5. run tshy
6. merge the cached files into dist

**Comment by isaacs** [comment]
I looked into how this might be accomplished with tshy, and it gets pretty hairy.

Since tsc itself doesn't have a way to say "remove comments for code, but not for declarations", you necessarily have to run tsc multiple times to do this, since you can't emit declarations-with-comments and code-without-comments in the same build. Tshy already runs tsc a bunch of times, so that's not in itself a terrible thing, but the tricky bit is how to specify this in the options in a way that's not horribly confusing and complicated.

It makes me wonder if it wouldn't be better to either just accept comments in the code, or have a separate build process that runs after tshy to strip comments from the JS.

**Comment by svallory** [comment]
What if "types" was treated as a dialect?

Then combined with a `tsconfig` that is configured to emit declaration only, to its own folder we would get a `dist/types` folder

In fact, this makes me think that maybe the idea of a dialects is the best thing about tshy and could be the starting point of everything.

The mental model would be that tshy works like a chef and dialects are like recipes.

Each recipe would have steps like

- use this tsconfig
- then exclude these files
- create temp package.json for dialect D
- temp link package in dist/D/node_modules/P
- etc

Of course there could be ready to use recipes for the base cases, but a structure like this could allow for infinite customization and reduce the burden of adding features for each case

Especially if steps have an interface and someone can provide their own

**Comment by isaacs** [comment]
> Then combined with a tsconfig that is configured to emit declaration only, to its own folder we would get a dist/types folder

The problem there is that "types" need to be specific to a given dialect build. In most cases, you cannot use the same type declarations for both CJS and ESM - even when it seems to work, and the .d.ts files are identical, it can cause weird behavior and incorrect behavior in both the compiler and language server. So it wouldn't make much sense to have a `dist/types` folder, since the types have to be unique to each dialect.

**Comment by svallory** [comment]
> The problem there is that "types" need to be specific to a given dialect build

That's right. I just remembered that default exports are different between the dialects. But do you know of any other issue? I've been only using named exports and thought it would be ok to share the types.

**Comment by isaacs** [comment]
> I've been only using named exports and thought it would be ok to share the types.

I think there's some issues there as well, even if you don't use a default export, because it'll yell at you if you are trying to require() a file where it thinks the types are ESM, or vice versa. But yes, it's completely broken if you do use default exports.

**Comment by isaacs** [comment]
I took another look at this, and I really think the solution here is either:

1. Build multiple times (eg, once with declarations only, then a second time with `"declarations": false, "stripComments": true`)
2. Likely much faster, just let tsc build with comments, and then use a bundler of some sort to strip them out. The only sticky bit there is making sure that the sourcemaps are preserved properly, but I believe most codemod tools these days can handle that, and most tools that can resolve sourcemaps at all are able to handle multi-stage sourcemaps, though of course you're likely to have to do a bit of tweaking to get it working just right.

I don't think I'll add support for this directly to tshy, but if you explore one of these options and there's something that could be done to make it easier, I'm happy to consider it. One thing that occurs to me is maybe tshy should let its project config be overridden by a `TSHY_PROJECT=<file>` environment variable or something, to at least make (1) a little easier to accomplish. The only challenge is that the base tsconfig file gets written to `.tshy/build.json`, and that can be annoying if you're swapping back and forth quickly.
