### ISSUE TITLE
Preserve `package.json` indentation

### ISSUE THREAD

**Issue by tommy-mitchell** [isaacs/tshy#46]
I use tab indentation in my projects, but `tshy` is configured to always re-indent `package.json` with two spaces:

https://github.com/isaacs/tshy/blob/bfaefec6e66197d7e3a578baa8ea4317ad1ade0b/src/write-package.ts#L4-L5

The [`detect-indent`](https://github.com/sindresorhus/detect-indent) package seems like a good fit for this. I'd be happy to make a PR.

**Comment by isaacs** [comment]
Used `polite-json`, since it does the stringifying automatically using the indentation it detected when parsing.
