### ISSUE TITLE
Respect package.json type

### ISSUE THREAD

**Issue by starnayuta** [isaacs/tshy#47]
If type is set to `commonjs` in package.json, this should be respected.  
Currently, type is always changed to `module`.

For example, during the migration of the commonjs library, we want the project type to be `commonjs`.

**Comment by boneskull** [comment]
I'm curious about the use-case for this

**Comment by isaacs** [comment]
@boneskull Well, it could be that your tests and scripts are all written in commonjs, or something like that, so it's easier to just have the package.json default to that.

**Comment by isaacs** [comment]
Fixed on 1.12
