### ISSUE TITLE
tshy --watch builds thrice

### ISSUE THREAD

**Issue by boneskull** [isaacs/tshy#49]
`tshy --watch` builds no less than three (3) times when I start it.  I am assuming that's not what should happen.

```shell
tshy --watch
build success { code: 0, signal: null }
build success { code: 0, signal: null }
build success { code: 0, signal: null }
```

(`node_modules/.bin` is in my `PATH`.)

If you can't reproduce this, [here's where I'm using it](https://github.com/boneskull/snapshot-fs).

**Comment by isaacs** [comment]
Haha, it seems like it's picking up the changes it's creating, resulting in an infinite loop of building. Which, I guess technically does mean it's building whenever you change things, but probably a bit more than is strictly necessary 😅

**Comment by isaacs** [comment]
I see what's happening. It's changing the `./package.json` file in the build. We _do_ need to rebuild if you change the package.json, but _not_ if tshy itself changes it. And the signal that a file was changed happens _after_ the build has completed, so it's a bit tricky. There's a 50ms delay in there before it sets `building=false`, but that is a bit kludgey, and seems to not be enough time anyway.
