### ISSUE TITLE
Excluding Files from Build, Targeted Builds

### ISSUE THREAD

**Issue by shellscape** [isaacs/tshy#59]
I've got a project where I have to build artifacts in the same `src` directory: the primary module, and the CLI for the module. The ideal setup is that the primary module is compiled to both commonjs and esm, but the CLI is built only with esm (as the `"bin"` property in package.json references only the esm build). Right now, tshy is attempting to include the CLI in the commonjs output and it's throwing all kinds of errors like:

```
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("vite")' call instead.
```

I don't want tshy to consider commonjs for the CLI at all. How can this be accomplished with tshy?

**Comment by isaacs** [comment]
Yup! Just name it .mjs and it'll only be esm.
