### ISSUE TITLE
Using glob should not override tshy.exports on run

### ISSUE THREAD

**Issue by novascreen** [isaacs/tshy#63]
I was trying the glob exports with a config like this:

```
"tshy": {
  "exports": "./src/**"
}
```

unfortunately when i run `tshy` it overrides `tshy.exports` with the results of the glob. So next time I want to add a file, i'll have to change it back to `"./src/**"`, which kind of defeats the purpose.

I would expect it to change `exports`, but not `tshy.exports`.

**Comment by isaacs** [comment]
Ah, yeah, that's annoying. The whole point is that you want to add files and not update anything.
