### ISSUE TITLE
Proposal: support `publishConfig`

### ISSUE THREAD

**Issue by colinhacks** [isaacs/tshy#65]
In my TypeScript monorepos like to point each package's `"exports"` field at raw `.ts` source files so VS Code will reflect "live" types even across package boundaries: https://colinhacks.com/essays/live-types-typescript-monorepo 

I'd love a `tshy` mode that writes `main`, `exports`, etc into `"publishConfig"` instead of the top-level fields: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#publishconfig 

If you're amenable, I'm happy to put in the PR for this but just wanted a sign-off first.

**Comment by isaacs** [comment]
Yeah, but if you publish it with those fields there, it won't do what you're implying. It won't be useable when it's installed from the registry. `publishConfig` only overrides _npm config values_ at publish time, not package.json fields.

**Comment by colinhacks** [comment]
That...is disappointing. I read the pnpm docs which explicitly supports all these fields: https://pnpm.io/package_json#publishconfig, then saw that same field in the npm docs and assumed the behavior was generally compatible. Not so. 💀

So yeah, a `publishConfig` mode is pretty useless. Sad.

**Comment by colinhacks** [comment]
New proposal: https://github.com/isaacs/tshy/issues/66
