### ISSUE TITLE
Proposal: `"sourceDialects"`

### ISSUE THREAD

**Issue by colinhacks** [isaacs/tshy#66]
This is a second proposal to solve the core problem described here: https://github.com/isaacs/tshy/issues/65. Namely, I'm trying to construct a TypeScript monorepo with "live types" across package boundaries.

To do this, I'm now attempting to a custom `"typescript"` export condition that points to my TypeScript source code. I can then configure [compilerOptions.customConditions](https://www.typescriptlang.org/tsconfig/#customConditions) such that TypeScript looks at the raw `.ts` source of my local packages in development instead of the `.d.ts` artifacts.

My proposal for achieving this is a "sourceDialects" field under `"tshy"`. 

```json
  "tshy": {
    "exports": {
      "./package.json": "./package.json",
      ".": "./src/index.ts"
    },
    "sourceDialects": [ "ts" ] 
  },
```

This would add a reference to the original entrypoint under the listed conditions:

```json
{
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "import": {
        "source": "./src/index.ts",
        "types": "./dist/esm/index.d.ts",
        "default": "./dist/esm/index.js"
      },
      "require": {
        "source": "./src/index.ts",
        "types": "./dist/commonjs/index.d.ts",
        "default": "./dist/commonjs/index.js"
      },
    }
  }
}
```

Other naming proposals: 

- "srcDialects": Fairly clear, I think, and not coupled to TypeScript 
- "tsConditions": Since there's no canonical condition for `.ts` source, the term "dialect" is perhaps not applicable
- "sourceConditions": I've seen others use `"source"` as a custom condition name

As before, happy to put in this PR but looking for a sign off & naming thoughts first.

**Comment by isaacs** [comment]
Ahh, yes, dependencies. You won't want their source, usually. It might work a lot of the time, but not always, so that's a footgun.
