### ISSUE TITLE
Add module field to package.json in ESM mode

### ISSUE THREAD

**Issue by smorimoto** [isaacs/tshy#76]
It’s a fallback entry point for ESM, and although it’s not officially supported by Node.js, the bundler continues to support it for historical reasons. Some applications, such as Strapi, may break without this.

Ref: https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for

**Comment by isaacs** [comment]
So it's just `dist/esm/index.m?js` if that exists? Patch welcome.

**Comment by smorimoto** [comment]
That should be fine. I'm already in bed, so when I get up I'll work on it if no one has risen the patch yet 🙂

**Comment by smorimoto** [comment]
@isaacs I'm a little busy this week, so if you don't mind, could you take care of this?

**Comment by isaacs** [comment]
Someone will get to it eventually lol, don't worry.

**Comment by smorimoto** [comment]
Indeed 😅

**Comment by isaacs** [comment]
Landed on 1.17, thanks Matt

**Comment by smorimoto** [comment]
Nice!
