### ISSUE TITLE
TS Config not respected when building with tshy

### ISSUE THREAD

**Issue by louiss0** [isaacs/tshy#89]
I was trying out this library when I found this error.

```sh
src/classMapChangers.ts:9:8 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './ClassNameMaps.js'?

9 } from "./ClassNameMaps";
         ~~~~~~~~~~~~~~~~~
```

My `moduleResolution` is **bundler** not **node** 

I don't know why this is happening.

The github repo is on https://github.com/louiss0/cn-efs

You need to switch to a branch called legacy to see it.

**Comment by isaacs** [comment]
Tshy isn't compatible with `type: "bundler"`. It hard codes "NodeNext".
