### ISSUE TITLE
More flatten output folder structure

### ISSUE THREAD

**Issue by Cellule** [isaacs/tshy#92]
I've found over the years that having a different folder structure relative to the root between the `src` folder and the `dist/esm` (or `dist/commonjs`) folders often leads to numerous issues with relative imports or file access.
This is shown by the need to have a library like [package-json-from-dist](https://www.npmjs.com/package/package-json-from-dist)

However, a very simple solution that I've found solves this without the need for additional "where's my root" logic is to have the output of the esm and commonjs at the same level as `src`
The resulting folder structure would look like

```
- root
  - src
    - Sources 
  - dist-esm
  	- Output for ESM
  - dist-commonjs
    - Output for CommonJS
  - package.json
```

The exports can then refer to `dist-esm` instead of `dist/esm` and so on. 
Usually only requiring a small modification to the .gitignore file to ignore both `dist-*` folders

Then it allows to safely use `__dirname` or `import.meta.url` (`import.meta.dirname` on Node 20.11 if I recall) to find files at the root relative to `src` folder like `package.json`

Related https://github.com/isaacs/package-json-from-dist/issues/1 https://github.com/isaacs/rimraf/issues/317

**Comment by isaacs** [comment]
This is not the appropriate solution to make package-json-from-dist work with yarn v4, and would clutter up the project root in an annoying way. It's better to have just one thing to ignore in git and include in npm.
