### ISSUE TITLE
Issue bundling src code with "zx" package / `{"type": "module"}` issue.

### ISSUE THREAD

**Issue by reggi** [isaacs/tshy#97]
Without `{"type": "module"}` and run `tsc --noEmit` I get this error:

```
src/deps.ts:1:21 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("zx")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/Users/thomasreggi/Desktop/commands/packages/command-center/package.json'.

1 import {which} from 'zx'
                      ~~~~

Found 1 error in src/deps.ts:1
```

Adding `{"type": "module"}`  all good ✅ 

When I run `npm run prepare` aka `tshy` I get the same error regardless of `{"type": "module"}` .

This is because durning the script, it's creating a `./src/package.json` file with `{"type": "commonjs"}` 🥲

The only workaround is to use a `.mts` files.

The fix should be to check the root package.json and get the type from there.

**Comment by reggi** [comment]
I keep getting this too, i feel like I'm missing 💀 

```
error TS18003: No inputs were found in config file '/Users/thomasreggi/Desktop/commands/packages/command-center/.tshy/commonjs.json'. Specified 'include' paths were '["../src/**/*.ts","../src/**/*.cts","../src/**/*.tsx","../src/**/*.json"]' and 'exclude' paths were '["../src/**/*.mts","../src/package.json"]'.

```

**Comment by reggi** [comment]
When I just covert the 3 files i have that link up to zx to `.mts` it works ✅ 
When I convert the whole project to `.mts` it fails ❌ the project needs at least one `.ts` file 😢

**Comment by isaacs** [comment]
If you don't want to build a hybrid module (ie both esm and commonjs) then you really don't need to use tshy, which is a typescript hybridizer

if you want tshy to only build one sort of dialect, you can put `"tshy": { "dialects": ["esm"] }` in package.json.

If you want to use a module that is only esm, from both esm and CJS, you'll need to use a dynamic import.

**Comment by reggi** [comment]
I want esm and commonjs 

zx is not a esm only module though zx has exports require that point to cjs (but it also has type module)

https://github.com/google/zx/blob/main/package.json
